const C=window.TODAY_CONFIG||{};const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey);const APP_VERSION='18.1.21';
const KINDS=['question','game','song','mystery','challenge','debate','duel','story','fact','trend','moment','footprint'];
const META={question:['ВОПРОС ДНЯ','?'],game:['ИГРА ДНЯ','🎮'],song:['ТВОЯ ПЕСНЯ СЕГОДНЯ','♫'],mystery:['ТАЙНА ДНЯ','◌'],challenge:['ЧЕЛЛЕНДЖ ДНЯ','⚡'],debate:['СПОР ДНЯ','◈'],duel:['ДУЭЛЬ МНЕНИЙ','⚔'],story:['ИСТОРИЯ ДНЯ','✎'],fact:['ФАКТ ДНЯ','!'],trend:['ТРЕНД ДНЯ','↗'],moment:['МОМЕНТ ДНЯ','◉'],footprint:['ОСТАВЬ СЛЕД','✦']};
const state={session:null,profile:null,day:'',items:[],stats:new Map(),deferredPrompt:null,booted:false,lastPresence:0};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function dayMoscow(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function moscowParts(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Moscow',hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}).formatToParts(new Date());return Object.fromEntries(p.map(x=>[x.type,x.value]))}
function tick(){const p=moscowParts(),h=Number(p.hour),m=Number(p.minute),s=Number(p.second),passed=h*3600+m*60+s,remain=Math.max(0,86400-passed),pct=Math.round(passed/864);$('countdown').textContent=`${String(Math.floor(remain/3600)).padStart(2,'0')}:${String(Math.floor(remain/60)%60).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}`;$('dayProgress').textContent=pct+'%';$('progressBar').style.width=pct+'%';if(dayMoscow()!==state.day){loadDay(true)}}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(){ $('modal').classList.add('hidden');$('modalContent').innerHTML='';document.body.style.overflow=''}
function requireAuth(){if(state.session)return true;openModal(`<div class="eyebrow">АККАУНТ</div><h2 id="modalTitle">Войти в TODAY</h2><p class="small-note">Сначала попробуй TODAY, а аккаунт нужен только чтобы сохранить свои ответы и публикации.</p><div class="composer"><input id="authEmail" type="email" autocomplete="email" placeholder="email"><input id="authPass" type="password" autocomplete="current-password" placeholder="пароль"><div class="composer-row"><button class="primary-button" onclick="authSignIn()">ВОЙТИ</button><button class="secondary-button" onclick="authSignUp()">СОЗДАТЬ</button></div></div>`);return false}
async function ensureProfile(){if(!state.session)return null;const {data,error}=await sb.from('profiles').select('*').eq('id',state.session.user.id).maybeSingle();if(!error)state.profile=data||null;updateAccountUI();return state.profile}
function updateAccountUI(){const avatar=$('profileAvatar'),label=$('profileLabel');if(state.session){avatar.textContent=state.profile?.avatar_emoji||'✦';label.textContent=state.profile?.display_name?.slice(0,16)||'МОЙ TODAY'}else{avatar.textContent='✦';label.textContent='АККАУНТ'}}
async function authSignIn(){const email=$('authEmail')?.value.trim(),password=$('authPass')?.value;if(!email||!password)return toast('Заполни email и пароль');const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);closeModal();await refreshSession();toast('С возвращением')}
async function authSignUp(){const email=$('authEmail')?.value.trim(),password=$('authPass')?.value;if(!email||password.length<6)return toast('Нужен email и пароль от 6 символов');const {error}=await sb.auth.signUp({email,password});if(error)return toast(error.message);closeModal();toast('Аккаунт создан. Если включено подтверждение email — проверь почту.');await refreshSession()}
async function refreshSession(){const {data}=await sb.auth.getSession();state.session=data.session;await ensureProfile();updateAccountUI()}
function countFor(id){return state.stats.get(id)||0}
function cardLayout(kind,index){if(index===0)return 'featured';if(index===1)return 'secondary';return 'standard'}
function bodyCopy(x){if(x.kind==='mystery')return '<div class="notice">Три подсказки. Ответ откроется постепенно.</div>';if(x.kind==='debate')return `<p>${esc(x.body)}</p><div class="card-kicker">Открой блок, прочитай аргументы и добавь свой.</div>`;if(x.kind==='song')return '<p>Одна ссылка на песню, которую ты слушаешь сегодня.</p>';if(x.kind==='moment')return '<p>Одно красивое фото сегодняшнего дня.</p>';if(x.kind==='trend')return `<p>${esc(x.body||'Поделись тем, что неожиданно оказалось в тренде.')}</p>`;return `<p>${esc(x.body||'Сегодня здесь начинается новая история.')}</p>`}
function actionFor(x){const id=x.id;if(x.kind==='question'||x.kind==='duel')return `<button class="primary-button" onclick="voteOpen('${id}')">ОТВЕТИТЬ</button>`;if(x.kind==='game')return `<button class="primary-button" onclick="gameOpen('${id}')">ИГРАТЬ</button>`;if(x.kind==='mystery')return `<button class="primary-button" onclick="mysteryOpen('${id}')">ОТКРЫТЬ ТАЙНУ</button>`;if(x.kind==='challenge')return `<button class="primary-button" onclick="challengeOpen('${id}')">ПРИНЯТЬ</button>`;if(x.kind==='debate')return `<button class="primary-button" onclick="debateOpen('${id}')">ОТКРЫТЬ СПОР</button>`;if(['song','story','fact','trend','moment','footprint'].includes(x.kind))return `<button class="primary-button" onclick="contribOpen('${id}','${x.kind}')">ДОБАВИТЬ СВОЁ</button>`;return ''}
async function loadDay(force=false){const next=dayMoscow();if(!force&&state.day===next&&state.items.length)return;state.day=next;$('dateLabel').textContent=next.split('-').reverse().join('.');const {data,error}=await sb.from('content_items').select('id,day_date,kind,title,body,payload,sort_order').eq('day_date',next).order('sort_order',{ascending:true});if(error){$('dailyGrid').innerHTML='<div class="notice">Не удалось загрузить TODAY. Обнови страницу.</div>';return}state.items=(data||[]).filter(x=>KINDS.includes(x.kind));renderItems();await Promise.all([loadStats(),loadCommunity(),loadLeaderboard()]);await touchPresence(true)}
function renderItems(){const grid=$('dailyGrid');grid.innerHTML='';if(state.items.length!==12){grid.innerHTML=`<div class="notice">Сегодняшний день ещё собирается. Сейчас доступно ${state.items.length}/12 рубрик.</div>`;return}state.items.forEach((x,i)=>{const [label,icon]=META[x.kind]||[x.kind,'•'];const card=document.createElement('article');card.className=`daily-card ${cardLayout(x.kind,i)} kind-${x.kind}`;card.innerHTML=`<div class="card-head"><span class="kind-pill">${icon} ${label}</span><span class="count-pill" id="count-${x.id}">${countFor(x.id)} сегодня</span></div><h3>${esc(x.title)}</h3><div class="card-body">${bodyCopy(x)}</div><div class="card-actions">${actionFor(x)}</div>`;grid.appendChild(card)})}
async function loadStats(){if(!state.day)return;const [stats,live]=await Promise.all([sb.rpc('today_interaction_stats',{p_day:state.day}),sb.rpc('today_live_count',{p_day:state.day})]);if(!stats.error){state.stats=new Map((stats.data||[]).map(r=>[r.content_id,Number(r.interactions||0)]));state.items.forEach(x=>{const el=$('count-'+x.id);if(el)el.textContent=countFor(x.id)+' сегодня'})}if(!live.error)$('liveCount').textContent=String(Number(live.data||0))+' человек сейчас'}
async function loadCommunity(){
  const feed=$('communityFeed');
  if(!feed||!state.day)return;
  let rows=[];
  try{
    const r=await sb.from('today_publications').select('id,user_id,kind,body,image_url,image_path,created_at').eq('day_date',state.day).order('created_at',{ascending:false}).limit(48);
    if(!r.error) rows=(r.data||[]).map(x=>({...x,source:'user',display_name:'Человек',avatar_emoji:'✦'}));
  }catch(e){console.warn('TODAY publications',e)}
  if(!rows.length){
    try{
      const r=await sb.from('daily_contributions').select('id,kind,body,image_path,created_at,profiles(display_name,avatar_emoji,avatar_url)').eq('day_date',state.day).order('created_at',{ascending:false}).limit(48);
      if(!r.error) rows=(r.data||[]).map(x=>({...x,source:'user',display_name:x.profiles?.display_name||'Человек',avatar_emoji:x.profiles?.avatar_emoji||'✦',avatar_url:x.profiles?.avatar_url||''}));
    }catch(e){console.warn('TODAY legacy feed',e)}
  }
  try{
    const r=await sb.from('demo_contributions').select('id,kind,body,image_url,created_at,display_name,avatar_emoji,avatar_url,bonus_title,bonus_icon,bonus_item_id').eq('day_date',state.day).order('created_at',{ascending:false}).limit(48);
    if(!r.error) rows=[...rows,...(r.data||[]).map(x=>({...x,source:'bot',display_name:x.display_name||'TODAY',avatar_emoji:x.avatar_emoji||'✦'}))];
  }catch(e){console.warn('TODAY bot feed',e)}
  rows.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));
  if(!rows.length){feed.innerHTML='<div class="notice">Сегодня здесь появится то, что оставят люди.</div>';return}
  feed.innerHTML=rows.slice(0,48).map(r=>{
    const label=META[r.kind]?.[0]||r.kind;
    const body=r.kind==='song'&&r.body?`<a href="${esc(r.body)}" target="_blank" rel="noopener noreferrer">Открыть песню ↗</a>`:esc(r.body||'');
    const image=r.image_url||r.image_path||'';
    const avatar=r.avatar_url?`<img src="${esc(r.avatar_url)}" alt="" loading="lazy">`:esc(r.avatar_emoji||'✦');
    return `<article class="community-card"><div class="community-head"><span class="community-avatar">${avatar}</span><span class="community-name">${esc(r.display_name||'Человек')}</span></div>${image?`<img src="${esc(image)}" alt="Фото TODAY" loading="lazy">`:''}<div class="community-copy"><div class="community-kind">${esc(label)}</div><p>${body||'Фото без подписи'}</p><div class="community-meta"><span>${esc(r.display_name||'Человек')}</span><span>сегодня</span></div></div></article>`
  }).join('');
}
async function loadLeaderboard(){const {data,error}=await sb.rpc('today_leaderboard',{p_day:state.day,p_limit:10});const el=$('leaderboard');if(error||!Array.isArray(data)||!data.length){el.innerHTML='<div class="notice">Рейтинг появится после первых действий.</div>';return}el.innerHTML=data.map((r,i)=>`<div class="rank-row"><div class="rank-number">${i+1}</div><div class="rank-name">${esc(r.display_name||'Человек')}</div><div class="rank-score">${Number(r.score||0)} XP</div></div>`).join('')}
function voteOpen(id){if(!requireAuth())return;const x=state.items.find(z=>z.id===id);const options=Array.isArray(x?.payload?.options)?x.payload.options:[];if(!x||!options.length)return toast('Для этой рубрики нет вариантов ответа');openModal(`<div class="eyebrow">${esc(META[x.kind]?.[0]||x.kind)}</div><h2 id="modalTitle">${esc(x.title)}</h2><p>${esc(x.body||'')}</p><div class="options">${options.map((o,i)=>`<button class="option-btn" onclick="vote('${id}',${i})">${esc(o)}</button>`).join('')}</div>`)}
async function vote(id,i){if(!requireAuth())return;const {error}=await sb.from('daily_votes').insert({day_date:state.day,user_id:state.session.user.id,content_id:id,option_index:i});if(error)return toast(error.code==='23505'?'Сегодня ты уже отвечал.':'Не удалось сохранить ответ');closeModal();toast('Ответ принят');await loadStats();await loadLeaderboard()}
function gameOpen(id){const x=state.items.find(z=>z.id===id),p=x?.payload||{};const options=Array.isArray(p.options)?p.options:[];openModal(`<div class="eyebrow">ИГРА ДНЯ</div><h2 id="modalTitle">${esc(x?.title||'Игра')}</h2><p>${esc(p.question||x?.body||'')}</p><div class="options">${options.map((o,i)=>`<button class="option-btn" onclick="gameAnswer('${id}',${i},${Number(p.answer_index??0)})">${esc(o)}</button>`).join('')}</div>`)}
async function gameAnswer(id,i,a){if(!requireAuth())return;const score=i===a?100:0;const {error}=await sb.from('game_attempts').insert({day_date:state.day,user_id:state.session.user.id,content_id:id,score});if(error)return toast(error.code==='23505'?'Эта игра уже сыграна.':'Не удалось сохранить игру');closeModal();toast(i===a?'Точно! +100 XP':'Сегодня не угадал');await loadStats();await loadLeaderboard()}
function mysteryOpen(id){const x=state.items.find(z=>z.id===id),clues=Array.isArray(x?.payload?.clues)?x.payload.clues:[],answer=String(x?.payload?.answer||'');openModal(`<div class="eyebrow">ТАЙНА ДНЯ</div><h2 id="modalTitle">${esc(x?.title||'Тайна')}</h2><p>${esc(x?.body||'')}</p><div id="mysteryBox" data-step="0"></div>`);window.__mystery={clues,answer};revealMystery()}
function revealMystery(){const box=$('mysteryBox');if(!box)return;const model=window.__mystery||{clues:[],answer:''};const step=Number(box.dataset.step||0)+1;box.dataset.step=String(step);if(step<=3){const clue=model.clues[step-1]||'Подсказка скрыта.';box.innerHTML=`<div class="clue"><b>Подсказка ${step}</b><br>${esc(clue)}</div>${step<3?`<button class="primary-button" style="margin-top:10px" onclick="revealMystery()">ОТКРЫТЬ ЕЩЁ</button>`:`<div class="notice" style="margin-top:10px"><b>Ответ:</b> ${esc(model.answer)}</div>`}`}}
async function challengeOpen(id){if(!requireAuth())return;const x=state.items.find(z=>z.id===id);openModal(`<div class="eyebrow">ЧЕЛЛЕНДЖ ДНЯ</div><h2 id="modalTitle">${esc(x?.title||'Челлендж')}</h2><p>${esc(x?.body||'')}</p><div class="card-actions"><button class="primary-button" onclick="challengeDo('${id}')">Я СДЕЛАЮ</button></div><div class="small-note">Одна попытка на сегодняшний челлендж.</div>`)}
async function challengeDo(id){if(!requireAuth())return;const {error}=await sb.from('challenge_submissions').insert({day_date:state.day,user_id:state.session.user.id,content_id:id});if(error)return toast(error.code==='23505'?'Ты уже принял этот челлендж.':'Не удалось сохранить');closeModal();toast('Челлендж принят');await loadStats();await loadLeaderboard()}
async function debateOpen(id){const x=state.items.find(z=>z.id===id);if(!x)return;const {data,error}=await sb.from('content_comments').select('id,body,created_at,profiles(display_name,avatar_emoji)').eq('content_id',id).eq('day_date',state.day).eq('hidden',false).order('created_at',{ascending:true}).limit(100);if(error)return toast('Не удалось открыть спор');const comments=data||[];openModal(`<div class="eyebrow">СПОР ДНЯ · ОТКРЫВАЕМЫЙ БЛОК</div><h2 id="modalTitle">${esc(x.title)}</h2><p>${esc(x.body||'')}</p><div class="comment-list">${comments.length?comments.map(c=>`<div class="comment"><small>${esc(c.profiles?.display_name||'Человек')}</small>${esc(c.body)}</div>`).join(''):'<div class="notice">Пока никто не начал спор. Стань первым.</div>'}</div>${state.session?`<div class="composer"><textarea id="commentText" maxlength="500" placeholder="Твой аргумент…"></textarea><div class="composer-row"><button class="primary-button" onclick="addComment('${id}')">ОТПРАВИТЬ</button></div><div class="small-note">Комментарий проходит серверную модерацию до публикации.</div></div>`:'<div class="notice">Войди в аккаунт, чтобы оставить комментарий.</div>'}`)}
async function addComment(id){if(!requireAuth())return;const body=$('commentText')?.value.trim();if(!body)return toast('Напиши аргумент');const fd=new FormData();fd.append('kind','debate_comment');fd.append('content_id',id);fd.append('body',body);const result=await moderateSend(fd);if(!result.ok)return toast(result.message);toast('Комментарий опубликован');await debateOpen(id);await loadStats();await loadLeaderboard()}
async function alreadySubmitted(kind){if(!state.session)return false;const {data}=await sb.from('daily_contributions').select('id').eq('day_date',state.day).eq('user_id',state.session.user.id).eq('kind',kind).maybeSingle();return Boolean(data)}
async function contribOpen(id,kind){if(!requireAuth())return;const x=state.items.find(z=>z.id===id);if(!x)return;try{if(await alreadySubmitted(kind))return toast('Сегодня ты уже добавлял сюда запись')}catch{}const cfg={song:['ТВОЯ ПЕСНЯ СЕГОДНЯ','Ссылка на одну песню, которую ты слушаешь сегодня.','url'],story:['ИСТОРИЯ ДНЯ','Одна история из твоего сегодняшнего дня.','text'],fact:['ФАКТ ДНЯ','Один факт, который тебя сегодня удивил.','text'],trend:['ТРЕНД ДНЯ','Расскажи, что необычного ты заметил. Можно текст или одно фото.','both'],moment:['МОМЕНТ ДНЯ','Одно красивое фото сегодняшнего дня.','image'],footprint:['ОСТАВЬ СЛЕД','Что интересного ты сделал сегодня?','text']}[kind];if(!cfg)return;const fields=cfg[2]==='url'?'<input id="contribUrl" type="url" placeholder="https://…">':cfg[2]==='image'?'<label class="file-label">Выбрать фото<input id="contribFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></label>':`<textarea id="contribBody" maxlength="1200" placeholder="Напиши здесь…"></textarea>${cfg[2]==='both'?'<label class="file-label">Добавить фото<input id="contribFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></label>':''}`;openModal(`<div class="eyebrow">${esc(cfg[0])}</div><h2 id="modalTitle">${esc(x.title)}</h2><p>${esc(cfg[1])}</p><div class="composer">${fields}<div class="notice">Одна публикация в этой рубрике за день. Фото проходят отдельную модерацию.</div><div class="composer-row"><button class="primary-button" onclick="sendContribution('${id}','${kind}')">ОТПРАВИТЬ</button></div></div>`)}
async function sendContribution(id,kind){if(!requireAuth())return;const fd=new FormData();fd.append('kind',kind);fd.append('content_id',id);if(kind==='song')fd.append('body',$('contribUrl')?.value.trim()||'');else if(kind!=='moment')fd.append('body',$('contribBody')?.value.trim()||'');const file=$('contribFile')?.files?.[0];if(file)fd.append('image',file);if(kind==='trend'&&!(fd.get('body')||file))return toast('Добавь текст или фото');if(kind==='song'){try{const u=new URL(fd.get('body'));if(!/^https?:$/.test(u.protocol))throw new Error()}catch{return toast('Нужна корректная ссылка https://…')}}const result=await moderateSend(fd);if(!result.ok)return toast(result.message);closeModal();toast('Опубликовано в TODAY');await Promise.all([loadCommunity(),loadStats(),loadLeaderboard()])}
async function moderateSend(fd){const token=(await sb.auth.getSession()).data.session?.access_token;if(!token){requireAuth();return {ok:false,message:'Нужен аккаунт'}}let response;try{response=await fetch(`${C.supabaseUrl.replace(/\/$/,'')}/functions/v1/moderate-content`,{method:'POST',headers:{apikey:C.supabaseKey,Authorization:`Bearer ${token}`},body:fd})}catch{return {ok:false,message:'Связь с модерацией недоступна'}}let jsonData={};try{jsonData=await response.json()}catch{}return response.ok?{ok:true,...jsonData}:{ok:false,message:jsonData.message||'Публикация отклонена модерацией'}}
async function touchPresence(force=false){if(!state.session)return;const now=Date.now();if(!force&&now-state.lastPresence<60000)return;state.lastPresence=now;try{await sb.from('presence').upsert({user_id:state.session.user.id,day_date:state.day,last_seen_at:new Date().toISOString()},{onConflict:'user_id'})}catch{}}
async function meOpen(){if(!requireAuth())return;await ensureProfile();const p=state.profile||{};openModal(`<div class="eyebrow">МОЙ TODAY</div><div class="profile-card"><div class="profile-row"><div class="profile-big">${esc(p.avatar_emoji||'✦')}</div><div><h2 id="modalTitle">${esc(p.display_name||'Ты')}</h2><div class="small-note">${esc(state.session?.user?.email||'')}</div></div></div><div class="profile-stats"><div class="profile-stat"><b>${Number(p.score_total||0)}</b><span>общий XP</span></div><div class="profile-stat"><b>${Number(p.level||1)}</b><span>уровень</span></div><div class="profile-stat"><b>${Number(p.streak||0)}</b><span>серия дней</span></div></div><div class="card-actions"><button class="secondary-button" onclick="signOut()">ВЫЙТИ</button></div></div>`)}
async function signOut(){await sb.auth.signOut();closeModal();state.session=null;state.profile=null;updateAccountUI();await loadLeaderboard();toast('Ты вышел из аккаунта')}
function setupNavigation(){document.querySelectorAll('.bottom-nav button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const target=btn.dataset.nav;if(target==='home')window.scrollTo({top:0,behavior:'smooth'});else if(target==='people')$('peopleSection').scrollIntoView({behavior:'smooth',block:'start'});else if(target==='rank')$('rankSection').scrollIntoView({behavior:'smooth',block:'start'});else if(target==='me'){state.session?meOpen():requireAuth()}}))}
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('installBtn').classList.add('hidden')}}
function setupModal(){ $('modalClose').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').classList.contains('hidden'))closeModal()})}
function notify(){if(!('Notification'in window))return toast('Этот браузер не поддерживает уведомления');Notification.requestPermission().then(v=>toast(v==='granted'?'Уведомления включены':'Уведомления не включены'))}
async function boot(){
  if(state.booted)return;
  state.booted=true;
  try{$('brandBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'})}catch(e){}
  try{$('profileBtn').onclick=()=>state.session?meOpen():requireAuth()}catch(e){}
  try{$('peopleRefresh').onclick=()=>loadCommunity()}catch(e){}
  try{$('notifyBtn').onclick=notify}catch(e){}
  try{setupNavigation();setupInstall();setupModal()}catch(e){console.warn('TODAY shell',e)}
  try{await refreshSession()}catch(e){console.warn('TODAY session init',e);state.session=null;try{updateAccountUI()}catch{}}
  try{await loadDay(true)}catch(e){console.error('TODAY loadDay',e);const g=$('dailyGrid');if(g)g.innerHTML='<div class="notice">Не удалось загрузить TODAY. Нажми обновить страницу.</div>'}
  try{tick()}catch(e){}
  setInterval(()=>{try{tick()}catch(e){}},1000);
  setInterval(()=>{try{touchPresence(false)}catch(e){}},60000);
  try{sb.auth.onAuthStateChange(async(_e,session)=>{state.session=session||null;try{await ensureProfile()}catch(e){}try{updateAccountUI()}catch(e){}try{await loadDay(true)}catch(e){console.warn('TODAY auth load',e)}})}catch(e){console.warn('TODAY auth listener',e)}
}
window.voteOpen=voteOpen;window.vote=vote;window.gameOpen=gameOpen;window.gameAnswer=gameAnswer;window.mysteryOpen=mysteryOpen;window.revealMystery=revealMystery;window.challengeOpen=challengeOpen;window.challengeDo=challengeDo;window.debateOpen=debateOpen;window.addComment=addComment;window.contribOpen=contribOpen;window.sendContribution=sendContribution;window.authSignIn=authSignIn;window.authSignUp=authSignUp;window.signOut=signOut;
boot().catch(e=>{console.error('TODAY boot fatal',e);try{const g=$('dailyGrid');if(g)g.innerHTML='<div class="notice">TODAY не удалось запустить. Обнови страницу.</div>'}catch{}});

/* TODAY V18.1.21 runtime guard */
window.addEventListener('error',e=>{console.error('TODAY runtime',e.error||e.message)});
window.addEventListener('unhandledrejection',e=>{console.error('TODAY promise',e.reason)});
