const C=window.TODAY_CONFIG;const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey);let STATE={session:null,items:[],day:'',selected:{},profile:null};
const KINDS=['question','game','song','mystery','challenge','debate','duel','story','fact','trend','moment','footprint'];
const META={question:['ВОПРОС ДНЯ','?'],game:['ИГРА ДНЯ','🎮'],song:['ТВОЯ ПЕСНЯ СЕГОДНЯ','♫'],mystery:['ТАЙНА ДНЯ','◌'],challenge:['ЧЕЛЛЕНДЖ ДНЯ','⚡'],debate:['СПОР ДНЯ','◈'],duel:['ДУЭЛЬ МНЕНИЙ','⚔'],story:['ИСТОРИЯ ДНЯ','✎'],fact:['ФАКТ ДНЯ','!'],trend:['ТРЕНД ДНЯ','↗'],moment:['МОМЕНТ ДНЯ','◉'],footprint:['ОСТАВЬ СЛЕД','✦']};
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>$('toast').classList.remove('show'),2800)}
function dayMoscow(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function tick(){const now=new Date(),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Moscow',hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}).formatToParts(now);let h=+parts.find(x=>x.type==='hour').value,m=+parts.find(x=>x.type==='minute').value,s=+parts.find(x=>x.type==='second').value;const rem=86400-(h*3600+m*60+s);$('countdown').textContent=`${String(Math.floor(rem/3600)).padStart(2,'0')}:${String(Math.floor(rem/60)%60).padStart(2,'0')}:${String(rem%60).padStart(2,'0')}`;$('dayProgress').textContent=Math.round((1-rem/86400)*100)+'%'}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden');$('modalContent').innerHTML=''}
async function ensureProfile(){if(!STATE.session)return null;let {data,error}=await sb.from('profiles').select('*').eq('id',STATE.session.user.id).maybeSingle();if(error)return null;if(!data){const name=(STATE.session.user.email||'user').split('@')[0].slice(0,24);const ins=await sb.from('profiles').insert({id:STATE.session.user.id,display_name:name,username:name.replace(/[^a-zA-Z0-9_а-яА-ЯёЁ]/g,'').slice(0,24)||null});if(!ins.error) data=ins.data?.[0]||null}STATE.profile=data;return data}
async function loadItems(){STATE.day=dayMoscow();$('dateLabel').textContent=STATE.day.split('-').reverse().join('.');let {data,error}=await sb.from('content_items').select('*').eq('day_date',STATE.day).order('sort_order',{ascending:true});if(error){toast('Не удалось загрузить TODAY');return}STATE.items=(data||[]).filter(x=>KINDS.includes(x.kind));renderItems();loadStats();loadCommunity()}
function cardClass(i){return i===0?'big':i===1?'mid':'small'}
function renderItems(){const grid=$('dailyGrid');grid.innerHTML='';STATE.items.forEach((x,i)=>{const [label,ico]=META[x.kind]||[x.kind,'•'];const card=document.createElement('article');card.className=`daily-card ${cardClass(i)}`;card.innerHTML=`<div class="card-head"><span class="kind-pill">${ico} ${label}</span><span class="count-pill" id="count-${x.id}">—</span></div><h3>${esc(x.title)}</h3><div class="card-body">${renderBody(x)}</div><div class="card-actions">${renderAction(x)}</div>`;grid.appendChild(card)})}
function renderBody(x){const p=x.payload||{};if(x.kind==='mystery')return `<div class="notice">Три подсказки. Ответ откроется только после третьей.</div>`;if(x.kind==='debate')return `<p>${esc(x.body)}</p><div class="notice">Открой спор и прочитай аргументы людей.</div>`;if(x.kind==='song')return `<p>Сегодня каждый может оставить одну песню, которую он слушает прямо сейчас.</p>`;if(['story','fact','trend','moment','footprint'].includes(x.kind))return `<p>${esc(x.body)}</p>`;return `<p>${esc(x.body)}</p>`}
function renderAction(x){if(x.kind==='question'||x.kind==='duel')return `<button class="primary-button" onclick="voteOpen('${x.id}')">ОТВЕТИТЬ</button>`;if(x.kind==='game')return `<button class="primary-button" onclick="gameOpen('${x.id}')">ИГРАТЬ</button>`;if(x.kind==='mystery')return `<button class="primary-button" onclick="mysteryOpen('${x.id}')">ОТКРЫТЬ</button>`;if(x.kind==='challenge')return `<button class="primary-button" onclick="challengeOpen('${x.id}')">ПРИНЯТЬ</button>`;if(x.kind==='debate')return `<button class="primary-button" onclick="debateOpen('${x.id}')">ОТКРЫТЬ СПОР</button>`;if(x.kind==='song')return `<button class="primary-button" onclick="contribOpen('${x.id}','song')">ДОБАВИТЬ ПЕСНЮ</button>`;if(x.kind==='story')return `<button class="primary-button" onclick="contribOpen('${x.id}','story')">РАССКАЗАТЬ</button>`;if(x.kind==='fact')return `<button class="primary-button" onclick="contribOpen('${x.id}','fact')">ДОБАВИТЬ ФАКТ</button>`;if(x.kind==='trend')return `<button class="primary-button" onclick="contribOpen('${x.id}','trend')">ПОДЕЛИТЬСЯ</button>`;if(x.kind==='moment')return `<button class="primary-button" onclick="contribOpen('${x.id}','moment')">ДОБАВИТЬ ФОТО</button>`;if(x.kind==='footprint')return `<button class="primary-button" onclick="contribOpen('${x.id}','footprint')">ОСТАВИТЬ СЛЕД</button>`;return ''}
function requireAuth(){if(!STATE.session){openModal(`<h3>Нужен аккаунт</h3><p>Войти или зарегистрироваться, чтобы оставить свой ответ.</p><div class="card-actions"><button class="primary-button" onclick="authOpen()">ВОЙТИ</button></div>`);return false}return true}
function authOpen(){openModal(`<h3>Твой аккаунт</h3><p>Введите email и пароль.</p><div class="composer"><input id="authEmail" type="email" placeholder="email"><input id="authPass" type="password" placeholder="пароль"><div class="composer-row"><button class="primary-button" onclick="authSignIn()">ВОЙТИ</button><button class="secondary-button" onclick="authSignUp()">СОЗДАТЬ</button></div></div>`)}
async function authSignIn(){const email=$('authEmail').value.trim(),password=$('authPass').value;if(!email||!password)return toast('Заполните email и пароль');let {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);closeModal();await boot()}
async function authSignUp(){const email=$('authEmail').value.trim(),password=$('authPass').value;if(!email||password.length<6)return toast('Нужен email и пароль от 6 символов');let {error}=await sb.auth.signUp({email,password});if(error)return toast(error.message);closeModal();toast('Аккаунт создан. Проверьте email, если подтверждение включено.');await boot()}
function authButton(){const b=$('profileBtn');b.onclick=()=>STATE.session?meOpen():authOpen()}
async function voteOpen(id){if(!requireAuth())return;const x=STATE.items.find(z=>z.id===id),opts=Array.isArray(x.payload?.options)?x.payload.options:[];openModal(`<h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div class="options">${opts.map((o,i)=>`<button class="option-btn" onclick="vote('${id}',${i})">${esc(o)}</button>`).join('')}</div>`)}
async function vote(id,i){if(!STATE.session)return requireAuth();const {error}=await sb.from('daily_votes').insert({day_date:STATE.day,user_id:STATE.session.user.id,content_id:id,option_index:i});if(error){toast(error.code==='23505'?'Ты уже отвечал сегодня.':'Не удалось сохранить ответ');return}closeModal();toast('Ответ принят');loadStats()}
function gameOpen(id){const x=STATE.items.find(z=>z.id===id),p=x.payload||{};openModal(`<h3>${esc(x.title)}</h3><p>${esc(p.question||x.body)}</p><div class="options">${(p.options||[]).map((o,i)=>`<button class="option-btn" onclick="gameAnswer('${id}',${i},${Number(p.answer_index||0)})">${esc(o)}</button>`).join('')}</div>`)}
async function gameAnswer(id,i,a){if(!STATE.session)return requireAuth();const score=i===a?100:0;const {error}=await sb.from('game_attempts').insert({day_date:STATE.day,user_id:STATE.session.user.id,content_id:id,score});if(error)return toast(error.code==='23505'?'Эта игра уже сыграна.':'Не удалось сохранить игру');closeModal();toast(i===a?'Точно! +100':'Сегодня не угадал.');loadStats()}
function mysteryOpen(id){const x=STATE.items.find(z=>z.id===id),clues=Array.isArray(x.payload?.clues)?x.payload.clues:[],answer=x.payload?.answer||'';openModal(`<h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div id="mysteryBox" data-step="0"></div>`);window.__mystery={clues,answer};revealMystery()};function revealMystery(){const b=$('mysteryBox');if(!b)return;const step=Number(b.dataset.step||0)+1;const m=window.__mystery||{clues:[],answer:''};b.dataset.step=String(step);if(step<=3){const c=m.clues[step-1]||'Подсказка отсутствует';b.innerHTML=`<div class="clue"><b>Подсказка ${step}</b><br>${esc(c)}</div>`+(step<3?`<button class="primary-button" style="margin-top:10px" onclick="revealMystery()">ОТКРЫТЬ ПОДСКАЗКУ ${step+1}</button>`:`<div class="notice" style="margin-top:10px"><b>Ответ:</b> ${esc(m.answer)}</div>`)} }
async function challengeOpen(id){if(!requireAuth())return;const x=STATE.items.find(z=>z.id===id);openModal(`<h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div class="card-actions"><button class="primary-button" onclick="challengeDo('${id}')">Я СДЕЛАЮ</button></div>`)}
async function challengeDo(id){const {error}=await sb.from('challenge_submissions').insert({day_date:STATE.day,user_id:STATE.session.user.id,content_id:id});if(error){toast(error.code==='23505'?'Челлендж уже принят.':'Не удалось сохранить');return}closeModal();toast('Челлендж принят. Сделай и возвращайся.');loadStats()}
async function debateOpen(id){const x=STATE.items.find(z=>z.id===id);let {data}=await sb.from('content_comments').select('id,body,created_at,profiles(display_name,avatar_emoji)').eq('content_id',id).eq('day_date',STATE.day).eq('hidden',false).order('created_at',{ascending:true}).limit(100);const comments=(data||[]);openModal(`<div class="eyebrow">СПОР ДНЯ</div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div class="comment-list">${comments.length?comments.map(c=>`<div class="comment"><small>${esc(c.profiles?.display_name||'Человек')}</small>${esc(c.body)}</div>`).join(''):'<div class="notice">Пока никто не начал спор. Напиши первым.</div>'}</div>${STATE.session?`<div class="comment-box"><textarea id="commentText" maxlength="500" placeholder="Твой аргумент…"></textarea><button class="primary-button" onclick="addComment('${id}')">ОТПРАВИТЬ</button></div>`:'<div class="notice">Чтобы писать в споре, войди в аккаунт.</div>'}`)}
async function addComment(id){if(!requireAuth())return;const body=$('commentText').value.trim();if(!body)return toast('Пустой комментарий');const form=new FormData();form.append('kind','debate_comment');form.append('content_id',id);form.append('body',body);const r=await moderateSend(form);if(!r.ok)return toast(r.message||'Комментарий удалён модерацией');toast('Комментарий опубликован');await debateOpen(id);loadStats()}
function contribOpen(id,kind){if(!requireAuth())return;const x=STATE.items.find(z=>z.id===id);const cfg={song:['Твоя песня сегодня','Вставь ссылку на одну песню, которую ты слушаешь сегодня.','url'],story:['История дня','Одна история из твоего дня.','text'],fact:['Факт дня','Один факт, который тебя сегодня удивил.','text'],trend:['Тренд дня','Что необычного ты сегодня увидел? Можно текстом или одним фото.','both'],moment:['Момент дня','Одно красивое фото сегодняшнего дня.','image'],footprint:['Оставь след','Что интересного ты сделал сегодня?','text']}[kind];openModal(`<div class="eyebrow">${esc(cfg[0])}</div><h3>${esc(x.title)}</h3><p>${esc(cfg[1])}</p><div class="composer">${cfg[2]==='url'?'<input id="contribUrl" placeholder="https://…">':''}${cfg[2]!=='url'&&cfg[2]!=='image'?'<textarea id="contribBody" maxlength="1200" placeholder="Напиши здесь…"></textarea>':''}${cfg[2]==='both'?'<label class="file-label">Добавить фото <input id="contribFile" type="file" accept="image/*" hidden></label>':''}${cfg[2]==='image'?'<label class="file-label">Выбрать фото <input id="contribFile" type="file" accept="image/*" hidden></label>':''}<div class="notice">За день можно оставить только одну публикацию в этой рубрике.</div><div class="composer-row"><button class="primary-button" onclick="sendContribution('${id}','${kind}')">ОТПРАВИТЬ</button></div></div>`)}
async function sendContribution(id,kind){const fd=new FormData();fd.append('kind',kind);fd.append('content_id',id);if(kind==='song')fd.append('body',$('contribUrl').value.trim());else if(kind!=='moment')fd.append('body',($('contribBody')?.value||'').trim());const f=$('contribFile')?.files?.[0];if(f)fd.append('image',f);const r=await moderateSend(fd);if(!r.ok)return toast(r.message||'Публикация не прошла модерацию');closeModal();toast('Опубликовано на сегодня');loadCommunity();loadStats()}
async function moderateSend(fd){const {data:{session}}=await sb.auth.getSession();if(!session){requireAuth();return {ok:false,message:'Нужен аккаунт'}}const r=await fetch(`${C.supabaseUrl.replace(/\/$/,'')}/functions/v1/moderate-content`,{method:'POST',headers:{apikey:C.supabaseKey,Authorization:`Bearer ${session.access_token}`},body:fd});let j={};try{j=await r.json()}catch{}return r.ok?{ok:true,...j}:{ok:false,message:j.message||'Содержимое отклонено модерацией'} }
async function loadCommunity(){let q=sb.from('daily_contributions').select('id,kind,body,image_path,created_at,profiles(display_name,avatar_emoji)').eq('day_date',STATE.day).order('created_at',{ascending:false}).limit(30);let {data}=await q;const feed=$('communityFeed');const rows=data||[];feed.innerHTML=rows.length?rows.map(r=>`<article class="community-card">${r.image_path?`<img src="${esc(r.image_path)}" alt="">`:''}<div class="community-copy"><div class="community-kind">${esc((META[r.kind]?.[0]||r.kind))}</div><p>${r.kind==='song'&&r.body?`<a href="${esc(r.body)}" target="_blank" rel="noopener noreferrer">${esc(r.body)}</a>`:esc(r.body||'')}</p><div class="community-meta">${esc(r.profiles?.display_name||'Человек')}</div></div></article>`).join(''):'<div class="notice">Сегодня здесь появится то, что оставят люди.</div>'}
async function loadStats(){if(!STATE.day)return;const live=await sb.rpc('today_live_count',{p_day:STATE.day});if(!live.error&&typeof live.data!=='undefined')$('liveCount').textContent=String(live.data||0)+' человек сейчас';for(const x of STATE.items){let rpc=null;if(x.kind==='question'||x.kind==='duel')rpc=sb.from('daily_votes').select('*',{count:'exact',head:true}).eq('content_id',x.id);else if(x.kind==='game')rpc=sb.from('game_attempts').select('*',{count:'exact',head:true}).eq('content_id',x.id);else if(x.kind==='challenge')rpc=sb.from('challenge_submissions').select('*',{count:'exact',head:true}).eq('content_id',x.id);else if(x.kind==='debate')rpc=sb.from('content_comments').select('*',{count:'exact',head:true}).eq('content_id',x.id);else rpc=sb.from('daily_contributions').select('*',{count:'exact',head:true}).eq('content_id',x.id);if(rpc){const {count}=await rpc;$(`count-${x.id}`).textContent=(count||0)+' сегодня'}}}
async function loadLeaderboard(){let {data}=await sb.rpc('today_leaderboard',{p_day:STATE.day, p_limit:10});const el=$('leaderboard');el.innerHTML=(data||[]).length?(data||[]).map((r,i)=>`<div class="rank-row"><div class="rank-number">${i+1}</div><div class="rank-name">${esc(r.display_name||'Человек')}</div><div class="rank-score">${Number(r.score||0)}</div></div>`).join(''):'<div class="notice">Пока рейтинг пуст.</div>'}
async function meOpen(){await ensureProfile();openModal(`<div class="profile-card"><div class="profile-row"><div class="profile-big">${esc(STATE.profile?.avatar_emoji||'✦')}</div><div><h3 style="margin:0">${esc(STATE.profile?.display_name||'Ты')}</h3><div class="small-note">${esc(STATE.session?.user?.email||'')}</div></div></div><div class="card-actions"><button class="secondary-button" onclick="sb.auth.signOut();closeModal();boot()">ВЫЙТИ</button></div></div>`)}
function nav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const n=b.dataset.nav;if(n==='people')$('community').scrollIntoView?.();else if(n==='rank')$('leaderboard').scrollIntoView?.();else if(n==='me'){if(STATE.session)meOpen();else authOpen()}else window.scrollTo({top:0,behavior:'smooth'})})}
function notify(){if('Notification'in window)Notification.requestPermission().then(x=>toast(x==='granted'?'Уведомления разрешены':'Уведомления не разрешены'))}
async function boot(){const {data}=await sb.auth.getSession();STATE.session=data.session;authButton();if(STATE.session)await ensureProfile();$('notifyBtn').onclick=notify;$('peopleRefresh').onclick=loadCommunity;await loadItems();await loadLeaderboard();tick();if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}setInterval(tick,1000);sb.auth.onAuthStateChange((_e,s)=>{STATE.session=s;authButton();loadLeaderboard()})}
$('modalClose').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});$('brandBtn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});nav();boot();