const C=window.TODAY_CONFIG||{};const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);const state={day:"",items:[],stats:new Map(),session:null,profile:null,deferredPrompt:null,lastPresence:0,shop:[],owned:[],booted:false};
const META={question:["Вопрос дня","?"],game:["Игра дня","⌁"],song:["Твоя песня сегодня","♫"],mystery:["Тайна дня","◈"],challenge:["Челлендж дня","⚡"],debate:["Спор дня","◐"],duel:["Дуэль мнений","VS"],story:["История дня","✎"],fact:["Факт дня","✦"],trend:["Тренд дня","↗"],moment:["Момент дня","▣"],footprint:["Оставь след","•"]};
const PARTICIPATING=new Set(["question","game","song","mystery","challenge","debate","duel","story","fact","trend","moment","footprint"]);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2600)}
function dayMoscow(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Moscow",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function dayOfYear(dateStr){const d=new Date(dateStr+"T12:00:00Z");const y=d.getUTCFullYear();const start=new Date(Date.UTC(y,0,1));return Math.floor((d-start)/86400000)+1}
function moscowParts(){const now=new Date();const f=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Moscow",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,weekday:"short"}).formatToParts(now);const o={};for(const p of f)o[p.type]=p.value;return o}
function tick(){const p=moscowParts();const left=(23-Number(p.hour))*3600+(59-Number(p.minute))*60+(60-Number(p.second));const total=86400;const remain=Math.max(0,left);$("countdown").textContent=[Math.floor(remain/3600),Math.floor(remain%3600/60),remain%60].map(n=>String(n).padStart(2,"0")).join(":");const used=total-remain;const pct=Math.min(100,Math.max(0,used/total*100));$("dayProgress").textContent=Math.round(pct)+"%";$("progressBar").style.width=pct+"%"}
function openModal(html){$("modalContent").innerHTML=html;$("modal").classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){$("modal").classList.add("hidden");document.body.style.overflow=""}
function requireAuth(){if(state.session)return true;openModal(`<div class="eyebrow">TODAY</div><h2 id="modalTitle">Сохрани своё место в дне</h2><p>Чтобы отвечать, публиковать и собирать монеты, войди или создай аккаунт.</p><div class="composer"><input id="authEmail" type="email" autocomplete="email" placeholder="Почта"><input id="authPassword" type="password" autocomplete="current-password" placeholder="Пароль"><div class="composer-row"><button class="primary-button" onclick="authSignIn()">ВОЙТИ</button><button class="secondary-button" onclick="authSignUp()">СОЗДАТЬ</button></div></div>`);return false}
async function ensureProfile(){if(!state.session)return;let {data}=await sb.from("profiles").select("id,display_name,username,avatar_emoji,avatar_url,streak,last_seen_date,coins,last_reward_date,score_total,level").eq("id",state.session.user.id).maybeSingle();if(!data){const email=state.session.user.email||"today";const local=email.split("@")[0].replace(/[^a-zA-Z0-9_а-яА-Я-]/g,"").slice(0,20)||"today";const ins=await sb.from("profiles").upsert({id:state.session.user.id,display_name:local,username:local,avatar_emoji:"✦",coins:0,streak:0,score_total:0,level:1},{onConflict:"id"}).select("id,display_name,username,avatar_emoji,avatar_url,streak,last_seen_date,coins,last_reward_date,score_total,level").single();data=ins.data||null}
 state.profile=data||null;updateAccountUI();await touchUserDay()}
function updateAccountUI(){const p=state.profile||{};$("profileLabel").textContent=state.session?(p.display_name||p.username||"ПРОФИЛЬ").toUpperCase():"АККАУНТ";$("coinCount").textContent=String(Number(p.coins||0));const av=$("profileAvatar");if(p.avatar_url)av.innerHTML=`<img src="${esc(p.avatar_url)}" alt="">`;else av.textContent=p.avatar_emoji||"✦";}
async function touchUserDay(){if(!state.session)return;try{const {data,error}=await sb.rpc("touch_user_day",{p_day:state.day});if(!error&&data){state.profile={...(state.profile||{}),...data};updateAccountUI();if(Number(data.reward||0)>0)toast(`Серия ${data.streak} дней · +${data.reward} монет`)}}catch{}}
async function authSignIn(){const email=$("authEmail")?.value.trim();const password=$("authPassword")?.value;if(!email||!password)return toast("Введи почту и пароль");const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);closeModal();toast("Добро пожаловать в TODAY")}
async function authSignUp(){const email=$("authEmail")?.value.trim();const password=$("authPassword")?.value;if(!email||!password)return toast("Введи почту и пароль");if(password.length<6)return toast("Пароль: минимум 6 символов");const {error}=await sb.auth.signUp({email,password});if(error)return toast(error.message);closeModal();toast("Аккаунт создан. Проверь почту, если включено подтверждение.")}
function setBackground(scene){const day=dayOfYear(state.day);const themes=[
 {name:"Сосновый лес",type:"forest",a:"#a8d5c7",b:"#2e5b4a",c:"#d7f0cc"},{name:"Тёплое море",type:"sea",a:"#75c8d4",b:"#206b85",c:"#f8da83"},{name:"Ночной город",type:"city",a:"#9a7cff",b:"#20204a",c:"#ffcf69"},{name:"Остров пальм",type:"palm",a:"#74d8c7",b:"#0e6966",c:"#ffd66a"},{name:"Горное утро",type:"mountain",a:"#bdd8ef",b:"#365777",c:"#f4e7bc"},{name:"Пустынный путь",type:"desert",a:"#f0c887",b:"#8f5134",c:"#ffe5a8"},{name:"Снег и свет",type:"snow",a:"#dcecff",b:"#527294",c:"#fff7d1"},{name:"Мокрый асфальт",type:"raincity",a:"#6975a4",b:"#1a2337",c:"#ff8b64"},{name:"Приморский вечер",type:"shore",a:"#8db3d6",b:"#274765",c:"#ffb86b"},{name:"Японский сад",type:"garden",a:"#c6e4cf",b:"#43694f",c:"#ed9fa2"},{name:"Звёздная ночь",type:"night",a:"#6c61a5",b:"#1c163b",c:"#f6e7b4"},{name:"Осенний парк",type:"park",a:"#e0a26e",b:"#69442d",c:"#f5cf73"},{name:"Крыши после дождя",type:"roofs",a:"#aab0c2",b:"#4a4c59",c:"#f6c0a6"},{name:"Утреннее поле",type:"field",a:"#b9da9c",b:"#547247",c:"#f8e3a5"},{name:"Сумеречное шоссе",type:"road",a:"#7d89b1",b:"#282e42",c:"#ffda72"},{name:"Озеро в тумане",type:"lake",a:"#adcfc6",b:"#315965",c:"#e6ead3"}];
 const t=themes[(day-1)%themes.length];let seed=day*7919+17;const rnd=()=>{seed=(seed*1664525+1013904223)%4294967296;return seed/4294967296};const W=1200,H=700;let bg=`<rect width="${W}" height="${H}" fill="${t.a}"/>`;bg+=`<rect y="500" width="${W}" height="200" fill="${t.b}"/>`;
 const rects=(n,y,base,w=70,h=90)=>{let s="";for(let i=0;i<n;i++){const x=Math.floor(rnd()*(W-w));const hh=Math.floor(h*(.65+.75*rnd()));s+=`<rect x="${x}" y="${y+(h-hh)}" width="${Math.max(18,w*(.35+.9*rnd()))}" height="${hh}" fill="${base}"/>`;}return s};
 if(["city","raincity","roofs"].includes(t.type)){bg+=rects(24,480,t.b,70,150);for(let i=0;i<80;i++){const x=Math.floor(rnd()*W/10)*10,y=390+Math.floor(rnd()*120/10)*10;bg+=`<rect x="${x}" y="${y}" width="6" height="6" fill="${t.c}" opacity="${.25+.65*rnd()}"/>`}}
 else if(["forest","garden","park","field"].includes(t.type)){for(let i=0;i<18;i++){const x=Math.floor(rnd()*W/20)*20;const h=110+Math.floor(rnd()*170);bg+=`<polygon points="${x},${500} ${x+55},${500-h} ${x+110},500" fill="${t.b}" opacity="${.5+.4*rnd()}"/>`;}bg+=`<rect y="535" width="1200" height="55" fill="${t.c}" opacity=".33"/>`}
 else if(["sea","shore","lake"].includes(t.type)){bg+=`<rect y="455" width="1200" height="95" fill="${t.b}" opacity=".42"/><rect y="550" width="1200" height="150" fill="${t.b}"/>`;for(let i=0;i<28;i++){let x=Math.floor(rnd()*W/20)*20,y=560+Math.floor(rnd()*100/10)*10;bg+=`<rect x="${x}" y="${y}" width="${30+Math.floor(rnd()*90)}" height="6" fill="${t.c}" opacity=".4"/>`}}
 else if(["mountain","desert","snow"].includes(t.type)){for(let i=0;i<7;i++){const x=i*190-60;const h=120+Math.floor(rnd()*160);bg+=`<polygon points="${x},500 ${x+120},${500-h} ${x+250},500" fill="${t.b}" opacity="${.55+.2*rnd()}"/>`;}if(t.type==="desert")for(let i=0;i<12;i++){let x=Math.floor(rnd()*W);bg+=`<rect x="${x}" y="${515+Math.floor(rnd()*120)}" width="${20+Math.floor(rnd()*50)}" height="5" fill="${t.c}" opacity=".35"/>`}}
 else if(t.type==="palm"){bg+=rects(8,500,t.b,90,150);for(let i=0;i<5;i++){const x=80+i*240;bg+=`<rect x="${x}" y="340" width="18" height="170" fill="${t.b}"/><polygon points="${x+9},340 ${x-80},300 ${x+95},315" fill="${t.c}"/><polygon points="${x+9},340 ${x+110},300 ${x+18},365" fill="${t.c}"/>`;}}
 else if(t.type==="night"){for(let i=0;i<70;i++){let x=Math.floor(rnd()*W/10)*10,y=Math.floor(rnd()*390/10)*10;bg+=`<rect x="${x}" y="${y}" width="5" height="5" fill="${t.c}" opacity="${.3+.7*rnd()}"/>`}}
 else if(t.type==="road"){bg+=`<polygon points="430,700 580,470 720,470 860,700" fill="#3f4655"/>`;for(let y=520;y<700;y+=45)bg+=`<rect x="${560-Math.floor((y-470)/2)}" y="${y}" width="80" height="14" fill="${t.c}" opacity=".7"/>`}
 else{bg+=rects(16,510,t.b,90,110)}
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" shape-rendering="crispEdges">${bg}<rect x="${Math.floor(rnd()*1000)}" y="${Math.floor(rnd()*250)}" width="26" height="26" fill="${t.c}" opacity=".22"/></svg>`;const img=document.createElement("img");img.className="daily-scene";img.alt="";img.src="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(svg);$("dailyBackdrop").replaceChildren(img);$("sceneName").textContent=`СЦЕНА ${day}/365`;$("sceneTitle").textContent=t.name;$("sceneMeta").textContent=`Пиксельный фон сегодня · вариант ${day}`;$("footerScene").textContent=t.name+" · фон №"+day}
function countFor(id){return state.stats.get(id)||0}
function cardLayout(i){return i===0?"featured":i===1?"secondary":"standard"}
function bodyCopy(x){if(x.kind==="mystery")return `<div class="notice">Три подсказки. Ответ откроется постепенно.</div>`;if(x.kind==="debate")return `<p>${esc(x.body)}</p><div class="card-kicker">Открой спор, прочитай мнения и добавь свой аргумент.</div>`;if(x.kind==="song")return `<p>Одна ссылка на песню, которую ты слушаешь сегодня.</p>`;if(x.kind==="moment")return `<p>Одно красивое фото сегодняшнего дня.</p>`;if(x.kind==="trend")return `<p>${esc(x.body||"Поделись тем, что неожиданно оказалось в тренде.")}</p>`;return `<p>${esc(x.body||"Сегодня здесь начинается новая история.")}</p>`}
function actionFor(x){const id=x.id;if(x.kind==="question"||x.kind==="duel")return `<button class="primary-button" onclick="voteOpen('${id}')">ОТВЕТИТЬ</button>`;if(x.kind==="game")return `<button class="primary-button" onclick="gameOpen('${id}')">ИГРАТЬ</button>`;if(x.kind==="mystery")return `<button class="primary-button" onclick="mysteryOpen('${id}')">ОТКРЫТЬ ТАЙНУ</button>`;if(x.kind==="challenge")return `<button class="primary-button" onclick="challengeOpen('${id}')">ПРИНЯТЬ</button>`;if(x.kind==="debate")return `<button class="primary-button" onclick="debateOpen('${id}')">ОТКРЫТЬ СПОР</button>`;if(["song","story","fact","trend","moment","footprint"].includes(x.kind))return `<button class="primary-button" onclick="contribOpen('${id}','${x.kind}')">ДОБАВИТЬ СВОЁ</button>`;return ""}
async function loadDay(force=false){const next=dayMoscow();if(!force&&state.day===next&&state.items.length)return;state.day=next;$("dateLabel").textContent=next.split("-").reverse().join(".");setBackground({});const {data,error}=await sb.from("content_items").select("id,day_date,kind,title,body,payload,sort_order").eq("day_date",next).order("sort_order",{ascending:true});if(error){$("dailyGrid").innerHTML=`<div class="notice">Не удалось загрузить сегодняшний день. Обнови страницу.</div>`;throw error}state.items=(data||[]).filter(x=>PARTICIPATING.has(x.kind));renderItems();await Promise.all([loadStats(),loadCommunity(),loadLeaderboard()]);await touchUserDay();}
function renderItems(){const grid=$("dailyGrid");grid.innerHTML="";if(state.items.length!==12){grid.innerHTML=`<div class="notice">Сегодняшний день готовится: ${state.items.length}/12 рубрик.</div>`;return}state.items.forEach((x,i)=>{const [label,icon]=META[x.kind];const card=document.createElement("article");card.className=`daily-card ${cardLayout(i)} kind-${x.kind}`;card.style.animationDelay=(i*45)+"ms";card.innerHTML=`<div class="card-head"><span class="kind-pill">${esc(icon)} ${esc(label)}</span><span class="count-pill" id="count-${x.id}">${countFor(x.id)} действий</span></div><h3>${esc(x.title)}</h3><div class="card-body">${bodyCopy(x)}</div><div class="card-actions">${actionFor(x)}</div>`;grid.appendChild(card)})}
async function loadStats(){if(!state.day)return;const [a,l]=await Promise.all([sb.rpc("today_interaction_stats",{p_day:state.day}),sb.rpc("today_live_count",{p_day:state.day})]);if(!a.error){state.stats=new Map((a.data||[]).map(r=>[r.content_id,Math.max(Number(r.total_votes||0),Number(r.total_actions||0))]));state.items.forEach(x=>{const el=$("count-"+x.id);if(el)el.textContent=countFor(x.id)+" действий"})}if(!l.error)$("liveCount").textContent=String(Number(l.data||0))}
function relativeTime(ts){const m=Math.max(0,Math.floor((Date.now()-new Date(ts).getTime())/60000));return m<1?"только что":m<60?`${m} мин назад`:`${Math.floor(m/60)} ч назад`}
async function loadCommunity(){const [real,demo]=await Promise.all([sb.from("daily_contributions").select("id,kind,body,image_path,created_at,profiles(display_name,avatar_emoji,avatar_url)").eq("day_date",state.day).order("created_at",{ascending:false}).limit(36),sb.from("demo_contributions").select("id,kind,body,image_url,created_at,display_name,avatar_emoji").eq("day_date",state.day).order("created_at",{ascending:false}).limit(36)]);const feed=$("communityFeed");if(real.error&&demo.error){feed.innerHTML='<div class="notice">Лента людей временно недоступна.</div>';return}const rows=[...(real.data||[]).map(r=>({...r,is_demo:false,display_name:r.profiles?.display_name||"Человек",avatar_emoji:r.profiles?.avatar_emoji||"✦",avatar_url:r.profiles?.avatar_url||""})),...(demo.data||[]).map(r=>({...r,is_demo:true,image_path:r.image_url}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,36);if(!rows.length){feed.innerHTML='<div class="notice">Сегодня здесь появится то, что оставят люди.</div>';return}$("activityTicker").textContent=`${rows[0].display_name} ${rows[0].kind==="song"?"поделился песней":"что-то оставил"} · ${relativeTime(rows[0].created_at)}`;feed.innerHTML=rows.map(r=>{const label=META[r.kind]?.[0]||r.kind;const image=r.image_path?`<img src="${esc(r.image_path)}" alt="Фото TODAY" loading="lazy">`:"";const body=r.kind==="song"&&r.body?`<a href="${esc(r.body)}" target="_blank" rel="noopener noreferrer">Открыть песню ↗</a>`:esc(r.body||"");return `<article class="community-card"><div>${image}</div><div class="community-copy"><div class="community-kind">${esc(label)}</div><p>${body||"Фото без подписи"}</p><div class="community-meta"><span>${esc(r.display_name||"Человек")}</span><span>${relativeTime(r.created_at)}</span></div></div></article>`}).join("")}
async function loadLeaderboard(){const {data,error}=await sb.rpc("today_leaderboard",{p_day:state.day,p_limit:10});const el=$("leaderboard");if(error||!Array.isArray(data)||!data.length){el.innerHTML='<div class="notice">Рейтинг появится после первых действий.</div>';return}el.innerHTML=data.map((r,i)=>`<div class="rank-row"><div class="rank-number">${i+1}</div><div class="rank-avatar">${r.avatar_url?`<img src="${esc(r.avatar_url)}" alt="">`:esc(r.avatar_emoji||"✦")}</div><div class="rank-name">${esc(r.display_name||r.username||"Человек")}</div><div class="rank-score">${Number(r.daily_score??r.score_total??0)} XP</div></div>`).join("")}
function voteOpen(id){if(!requireAuth())return;const x=state.items.find(z=>z.id===id);const options=Array.isArray(x?.payload?.options)?x.payload.options:[];openModal(`<div class="eyebrow">${esc(META[x.kind]?.[0]||"ВОПРОС")}</div><h2 id="modalTitle">${esc(x.title)}</h2><p>${esc(x.body||"")}</p><div class="options">${options.map((o,i)=>`<button class="option-btn" onclick="vote('${id}',${i})">${esc(o)}</button>`).join("")}</div>`)}
async function vote(id,i){if(!requireAuth())return;const {error}=await sb.from("daily_votes").insert({day_date:state.day,user_id:state.session.user.id,content_id:id,option_index:i});if(error)return toast(error.code==="23505"?"Сегодня ты уже отвечал.":"Не удалось сохранить ответ");closeModal();toast("Ответ принят · +5 XP");await Promise.all([loadStats(),loadLeaderboard(),touchUserDay()])}
function gameOpen(id){if(!requireAuth())return;const x=state.items.find(z=>z.id===id),p=x?.payload||{};const options=Array.isArray(p.options)?p.options:[];openModal(`<div class="eyebrow">ИГРА ДНЯ</div><h2 id="modalTitle">${esc(x?.title||"Игра")}</h2><p>${esc(p.question||x?.body||"")}</p><div class="options">${options.map((o,i)=>`<button class="option-btn" onclick="gameAnswer('${id}',${i},${Number(p.answer_index??0)})">${esc(o)}</button>`).join("")}</div>`)}
async function gameAnswer(id,i,a){if(!requireAuth())return;const score=i===a?100:0;const {error}=await sb.from("game_attempts").insert({day_date:state.day,user_id:state.session.user.id,content_id:id,score});if(error)return toast(error.code==="23505"?"Эта игра уже сыграна.":"Не удалось сохранить игру");closeModal();toast(i===a?"Точно! +100 XP":"Сегодня не угадал");await Promise.all([loadStats(),loadLeaderboard(),touchUserDay()])}
function mysteryOpen(id){const x=state.items.find(z=>z.id===id),p=x?.payload||{},clues=Array.isArray(p.clues)?p.clues:[],answer=String(p.answer||"");openModal(`<div class="eyebrow">ТАЙНА ДНЯ</div><h2 id="modalTitle">${esc(x?.title||"Тайна")}</h2><p>${esc(x?.body||"")}</p><div id="mysteryBox" data-step="0"></div>`);window.__mystery={clues,answer};revealMystery()}
function revealMystery(){const box=$("mysteryBox");if(!box)return;const m=window.__mystery||{clues:[],answer:""};const step=Number(box.dataset.step||0)+1;box.dataset.step=String(step);if(step<=3){box.innerHTML=`<div class="clue"><b>Подсказка ${step}</b><br>${esc(m.clues[step-1]||"Подсказка скрыта.")}</div>${step<3?`<button class="primary-button" style="margin-top:10px" onclick="revealMystery()">ОТКРЫТЬ ЕЩЁ</button>`:`<div class="notice" style="margin-top:10px"><b>Ответ:</b> ${esc(m.answer)}</div>`}`}}
function challengeOpen(id){if(!requireAuth())return;const x=state.items.find(z=>z.id===id);openModal(`<div class="eyebrow">ЧЕЛЛЕНДЖ ДНЯ</div><h2 id="modalTitle">${esc(x?.title||"Челлендж")}</h2><p>${esc(x?.body||"")}</p><div class="card-actions"><button class="primary-button" onclick="challengeDo('${id}')">Я СДЕЛАЮ</button></div><div class="small-note">Одна попытка на сегодняшний челлендж.</div>`)}
async function challengeDo(id){if(!requireAuth())return;const {error}=await sb.from("challenge_submissions").insert({day_date:state.day,user_id:state.session.user.id,content_id:id});if(error)return toast(error.code==="23505"?"Ты уже принял этот челлендж.":"Не удалось сохранить");closeModal();toast("Челлендж принят · +30 XP");await Promise.all([loadStats(),loadLeaderboard(),touchUserDay()])}
async function debateOpen(id){const x=state.items.find(z=>z.id===id);if(!x)return;const [real,demo]=await Promise.all([sb.from("content_comments").select("id,body,created_at,profiles(display_name,avatar_emoji,avatar_url)").eq("content_id",id).eq("day_date",state.day).eq("hidden",false).order("created_at",{ascending:true}).limit(100),sb.from("demo_comments").select("id,body,created_at,display_name,avatar_emoji").eq("content_id",id).eq("day_date",state.day).order("created_at",{ascending:true}).limit(100)]);const comments=[...(real.data||[]).map(c=>({...c,display_name:c.profiles?.display_name||"Человек"})),...(demo.data||[])].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const commentsHtml=comments.length?comments.map(c=>`<div class="comment"><small>${esc(c.display_name||"Человек")}</small><span>${esc(c.body)}</span></div>`).join(""):'<div class="notice">Пока никто не начал спор. Стань первым.</div>';let formHtml='<div class="notice">Войди в аккаунт, чтобы оставить комментарий.</div>';if(state.session){formHtml='<div class="composer"><textarea id="commentText" maxlength="500" placeholder="Твой аргумент…"></textarea><div class="composer-row"><button id="debateSend" class="primary-button">ОТПРАВИТЬ</button></div><div class="small-note">Комментарий проходит серверную модерацию до публикации.</div></div>';}const html=`<div class="eyebrow">СПОР ДНЯ · ОТКРЫТЫЙ БЛОК</div><h2 id="modalTitle">${esc(x.title)}</h2><p>${esc(x.body||"")}</p><div class="comment-list">${commentsHtml}</div>`+formHtml;openModal(html);if(state.session&&$("debateSend"))$("debateSend").onclick=()=>addComment(id)}
async function addComment(id){if(!requireAuth())return;const body=$("commentText")?.value.trim();if(!body)return toast("Напиши аргумент");const fd=new FormData();fd.append("kind","debate_comment");fd.append("content_id",id);fd.append("body",body);const result=await moderateSend(fd);if(!result.ok)return toast(result.message);toast("Комментарий опубликован · +5 XP");await debateOpen(id);await Promise.all([loadStats(),loadLeaderboard()])}
async function alreadySubmitted(kind){if(!state.session)return false;const {data}=await sb.from("daily_contributions").select("id").eq("day_date",state.day).eq("user_id",state.session.user.id).eq("kind",kind).maybeSingle();return Boolean(data)}
async function contribOpen(id,kind){if(!requireAuth())return;const x=state.items.find(z=>z.id===id);if(!x)return;try{if(await alreadySubmitted(kind))return toast("Сегодня ты уже добавлял сюда запись")}catch{}const cfg={song:["ТВОЯ ПЕСНЯ СЕГОДНЯ","Ссылка на одну песню, которую ты слушаешь сегодня.","url"],story:["ИСТОРИЯ ДНЯ","Одна история из твоего сегодняшнего дня.","text"],fact:["ФАКТ ДНЯ","Один факт, который тебя сегодня удивил.","text"],trend:["ТРЕНД ДНЯ","Расскажи, что необычного ты заметил. Можно текст или фото.","both"],moment:["МОМЕНТ ДНЯ","Одно красивое фото сегодняшнего дня.","image"],footprint:["ОСТАВЬ СЛЕД","Что интересного ты сделал сегодня?","text"]}[kind];const fields=cfg[2]==="url"?'<input id="contribUrl" type="url" placeholder="https://…">':cfg[2]==="image"?'<label class="file-label">Выбрать фото<input id="contribFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></label>':`<textarea id="contribBody" maxlength="1200" placeholder="Напиши здесь…"></textarea>${cfg[2]==="both"?'<label class="file-label">Добавить фото<input id="contribFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></label>':''}`;openModal(`<div class="eyebrow">${esc(cfg[0])}</div><h2 id="modalTitle">${esc(x.title)}</h2><p>${esc(cfg[1])}</p><div class="composer">${fields}<div class="notice">Одна публикация в этой рубрике за день. Текст и фото проходят серверную модерацию.</div><div class="composer-row"><button class="primary-button" onclick="sendContribution('${id}','${kind}')">ОТПРАВИТЬ</button></div></div>`)}
async function sendContribution(id,kind){if(!requireAuth())return;const fd=new FormData();fd.append("kind",kind);fd.append("content_id",id);if(kind==="song")fd.append("body",$("contribUrl")?.value.trim()||"");else if(kind!=="moment")fd.append("body",$("contribBody")?.value.trim()||"");const file=$("contribFile")?.files?.[0];if(file)fd.append("image",file);if(kind==="trend"&&!(fd.get("body")||file))return toast("Добавь текст или фото");if(kind==="song"){try{const u=new URL(fd.get("body"));if(!/^https?:$/.test(u.protocol))throw new Error()}catch{return toast("Нужна корректная ссылка https://…")}}const result=await moderateSend(fd);if(!result.ok)return toast(result.message);closeModal();toast("Опубликовано · +20 XP");await Promise.all([loadCommunity(),loadStats(),loadLeaderboard()])}
async function moderateSend(fd){const token=(await sb.auth.getSession()).data.session?.access_token;if(!token){requireAuth();return {ok:false,message:"Нужен аккаунт"}}try{const response=await fetch(`${String(C.supabaseUrl).replace(/\/$/,"")}/functions/v1/moderate-content`,{method:"POST",headers:{apikey:C.supabaseKey,Authorization:`Bearer ${token}`},body:fd});let data={};try{data=await response.json()}catch{}return response.ok?{ok:true,...data}:{ok:false,message:data.message||"Публикация отклонена модерацией"}}catch{return {ok:false,message:"Сервис модерации сейчас недоступен. Публикация не сохранена."}}}
async function touchPresence(){if(!state.session)return;const now=Date.now();if(now-state.lastPresence<60000)return;state.lastPresence=now;try{await sb.from("presence").upsert({user_id:state.session.user.id,day_date:state.day,last_seen_at:new Date().toISOString()},{onConflict:"user_id"})}catch{}}
async function saveProfile(){if(!requireAuth())return;const nickname=$("profileNick")?.value.trim();if(!nickname)return toast("Ник не может быть пустым");const fd=new FormData();fd.append("kind","profile");fd.append("content_id","profile");fd.append("nickname",nickname);const file=$("profileFile")?.files?.[0];if(file)fd.append("image",file);const result=await moderateSend(fd);if(!result.ok)return toast(result.message);await ensureProfile();toast("Профиль обновлён")}
function rewardRate(streak){if(streak>=100)return 10;if(streak>=50)return 5;if(streak>=20)return 4;if(streak>=10)return 2;if(streak>=5)return 1;return 0}
function rewardNext(streak){if(streak<5)return 5;if(streak<10)return 10;if(streak<20)return 20;if(streak<50)return 50;if(streak<100)return 100;return 365}
async function loadShop(){const [shop,owned]=await Promise.all([sb.from("shop_items").select("id,title,description,price_coins,icon,type,css_class,active").eq("active",true).order("price_coins",{ascending:true}),state.session?sb.from("user_shop_items").select("item_id,equipped").eq("user_id",state.session.user.id):Promise.resolve({data:[]})]);state.shop=shop.data||[];state.owned=owned.data||[];applyOwned()}
function applyOwned(){document.body.classList.remove("effect-neon","effect-orbit","effect-aurora");$("pet").classList.add("hidden");for(const o of state.owned){const item=state.shop.find(x=>x.id===o.item_id);if(!item||!o.equipped)continue;if(item.css_class)document.body.classList.add(item.css_class);if(item.type==="pet"){$("pet").textContent=item.icon||"🐈";$("pet").classList.remove("hidden")}}}
async function buyItem(itemId){if(!requireAuth())return;const {data,error}=await sb.rpc("buy_shop_item",{p_item_id:itemId});if(error)return toast(error.message||"Не удалось купить");toast("Предмет добавлен в коллекцию");await Promise.all([ensureProfile(),loadShop()]);shopOpen()}
async function equipItem(itemId){if(!requireAuth())return;const {error}=await sb.rpc("equip_shop_item",{p_item_id:itemId});if(error)return toast(error.message||"Не удалось надеть предмет");await loadShop();shopOpen();toast("Эффект применён")}
async function createCoinPayment(bundleId){if(!requireAuth())return;try{const token=(await sb.auth.getSession()).data.session?.access_token;const r=await fetch(`${C.supabaseUrl}/functions/v1/create-coin-payment`,{method:"POST",headers:{apikey:C.supabaseKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({bundle_id:bundleId,return_url:location.href.split("?")[0]})});const data=await r.json();if(!r.ok)return toast(data.message||"Оплата пока не подключена");if(data.confirmation_url)location.href=data.confirmation_url}catch{toast("Сервис оплаты пока не отвечает")}}
async function verifyReturnedPayment(){const q=new URLSearchParams(location.search);const order=q.get("order_id");if(!order)return;try{const token=(await sb.auth.getSession()).data.session?.access_token;if(!token)return;const r=await fetch(`${C.supabaseUrl}/functions/v1/verify-coin-payment`,{method:"POST",headers:{apikey:C.supabaseKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({order_id:order})});const data=await r.json();if(data.ok&&Number(data.coins)>0){toast(`Оплата подтверждена · +${data.coins} монет`);await ensureProfile()}history.replaceState({},"",location.pathname)}catch{}}
async function shopOpen(){if(!requireAuth())return;await Promise.all([ensureProfile(),loadShop()]);const p=state.profile||{};const items=state.shop.map(i=>{const owned=state.owned.some(x=>x.item_id===i.id);const eq=state.owned.some(x=>x.item_id===i.id&&x.equipped);return `<article class="shop-item"><div class="shop-icon">${esc(i.icon||"✦")}</div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><div class="shop-price">${owned?"У тебя есть":"● "+Number(i.price_coins)+" монет"}</div><div class="shop-buy-row">${owned?`<button class="secondary-button" onclick="equipItem('${i.id}')">${eq?"НАДЕТО":"НАДЕТЬ"}</button>`:`<button class="primary-button" onclick="buyItem('${i.id}')">КУПИТЬ</button>`}</div></article>`}).join("");openModal(`<div class="eyebrow">МАГАЗИН TODAY</div><h2 id="modalTitle">Твои монеты · ${Number(p.coins||0)}</h2><p>Покупай только визуальные вещи: они не дают преимущества в играх.</p><div class="shop-grid">${items}</div><div class="section-head" style="margin-top:22px"><div><div class="eyebrow">КУПИТЬ МОНЕТЫ</div><h3 style="margin:7px 0 0">1 ₽ = 1 монета</h3></div></div><div class="bundle-grid">${[[50,50],[300,250],[600,500],[1000,800],[5000,4500]].map((b,i)=>`<button class="bundle" onclick="createCoinPayment('b${i+1}')"><strong>${b[0]}</strong><span>${b[1]} ₽</span></button>`).join("")}</div><div class="small-note" style="margin-top:9px">Оплата откроется на защищённой странице платёжного сервиса, если ЮKassa подключена.</div></div>`)}
async function meOpen(){if(!requireAuth())return;await Promise.all([ensureProfile(),loadShop()]);const p=state.profile||{};const streak=Number(p.streak||0);const rate=rewardRate(streak);const target=rewardNext(streak);const pct=Math.min(100,streak/Math.max(1,target)*100);openModal(`<div class="eyebrow">МОЙ TODAY</div><div class="profile-card"><div class="profile-row"><div class="profile-big">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(p.avatar_emoji||"✦")}</div><div><h2 id="modalTitle">${esc(p.display_name||"Ты")}</h2><div class="small-note">@${esc(p.username||"today")}</div></div></div><div class="profile-stats"><div class="profile-stat"><b>${Number(p.score_total||0)}</b><span>общий XP</span></div><div class="profile-stat"><b>${Number(p.level||1)}</b><span>уровень</span></div><div class="profile-stat"><b>${streak}</b><span>серия дней</span></div><div class="profile-stat"><b>${Number(p.coins||0)}</b><span>монет</span></div></div><div class="reward-bar"><strong>${rate?`Серия ${streak} дней · сегодня +${rate} мон.`:"Дойди до 5 дней без пропусков — начнутся монеты."}</strong><div class="reward-track"><i style="width:${pct}%"></i></div><div class="small-note" style="margin-top:6px">Следующий рубеж: ${target} дней</div></div><div class="composer"><input id="profileNick" maxlength="32" value="${esc(p.display_name||"")}" placeholder="Твой ник"><label class="file-label">Фото аватара<input id="profileFile" type="file" accept="image/jpeg,image/png,image/webp" hidden></label><div class="composer-row"><button class="primary-button" onclick="saveProfile()">СОХРАНИТЬ</button><button class="secondary-button" onclick="shopOpen()">МАГАЗИН</button></div><div class="small-note">Ник и аватар проходят ту же строгую модерацию, что и публикации.</div></div><div class="card-actions"><button class="secondary-button" onclick="signOut()">ВЫЙТИ</button></div></div>`)}
async function signOut(){await sb.auth.signOut();closeModal();state.session=null;state.profile=null;state.owned=[];applyOwned();updateAccountUI();toast("Ты вышел из аккаунта")}
function setupNavigation(){document.querySelectorAll(".bottom-nav button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".bottom-nav button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const target=btn.dataset.nav;if(target==="home")window.scrollTo({top:0,behavior:"smooth"});else if(target==="people")$("peopleSection").scrollIntoView({behavior:"smooth",block:"start"});else if(target==="rank")$("rankSection").scrollIntoView({behavior:"smooth",block:"start"});else if(target==="me")state.session?meOpen():requireAuth()}))}
function setupInstall(){window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$("installBtn").classList.add("hidden")}}
function setupModal(){ $("modalClose").onclick=closeModal;$("modal").querySelector(".modal-backdrop").onclick=closeModal;window.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()})}
function notify(){if(!("Notification" in window))return toast("Уведомления не поддерживаются этим браузером");Notification.requestPermission().then(p=>toast(p==="granted"?"Уведомления включены":"Уведомления не разрешены"))}
async function purgeCache(){try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith("today-")&&k!=="today-static-today-172").map(k=>caches.delete(k)));if(navigator.serviceWorker){const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs)await reg.update()}}catch{}}
async function boot(){if(state.booted)return;state.booted=true;try{await purgeCache();$("brandBtn").onclick=()=>window.scrollTo({top:0,behavior:"smooth"});$("profileBtn").onclick=()=>state.session?meOpen():requireAuth();$("peopleRefresh").onclick=()=>loadCommunity();$("notifyBtn").onclick=notify;setupNavigation();setupInstall();setupModal();const s=await sb.auth.getSession();state.session=s.data.session||null;await loadDay(true);if(state.session)await ensureProfile();updateAccountUI();await verifyReturnedPayment();setInterval(tick,1000);setInterval(()=>touchPresence(),60000);tick();sb.auth.onAuthStateChange(async(_e,session)=>{state.session=session;await ensureProfile();updateAccountUI();await loadDay(true);await loadShop()});navigator.serviceWorker?.register("./sw.js?v=172").catch(()=>{})}catch(e){console.error(e);toast("TODAY не удалось запустить. Обнови страницу")}}
window.voteOpen=voteOpen;window.vote=vote;window.gameOpen=gameOpen;window.gameAnswer=gameAnswer;window.mysteryOpen=mysteryOpen;window.revealMystery=revealMystery;window.challengeOpen=challengeOpen;window.challengeDo=challengeDo;window.debateOpen=debateOpen;window.addComment=addComment;window.contribOpen=contribOpen;window.sendContribution=sendContribution;window.authSignIn=authSignIn;window.authSignUp=authSignUp;window.signOut=signOut;window.meOpen=meOpen;window.shopOpen=shopOpen;window.saveProfile=saveProfile;window.buyItem=buyItem;window.equipItem=equipItem;window.createCoinPayment=createCoinPayment;window.revealMystery=revealMystery;boot();
